# Generated by Django 4.1.1 on 2022-10-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('warehouse', '0002_remove_product_currency_id_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number_id', models.AutoField(db_column='number_id', primary_key=True, serialize=False)),
                ('address_order', models.CharField(db_column='address_order', max_length=50, verbose_name='Direccion de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Moficación')),
                ('client', models.ForeignKey(db_column='client_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Cliente')),
                ('products', models.ManyToManyField(db_column='products', to='warehouse.product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Orden de Pedido',
                'db_table': 'order',
            },
        ),
    ]
