# Generated by Django 4.1.1 on 2022-10-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_igv_order_subtotal_amount_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivered',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('enviado', 'enviado'), ('entregado', 'entregado'), ('pagado', 'pagado')], db_column='estados', default='enviado', max_length=10),
        ),
    ]
