# Generated by Django 4.1.1 on 2022-10-19 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_date_delivered_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='igv',
            field=models.DecimalField(blank=True, db_column='igv', decimal_places=2, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, db_column='subtotal', decimal_places=2, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='total', decimal_places=2, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0000'), max_digits=7, verbose_name='Total Descuento'),
        ),
    ]
