# Generated by Django 4.1.1 on 2022-10-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_product_code_alter_productcategory_code'),
        ('sales', '0005_alter_order_igv_alter_order_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_delivered',
            new_name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='number_order',
            field=models.CharField(db_column='number_order', default='', max_length=10, verbose_name='Numero de Pedido'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
            ],
            options={
                'verbose_name': 'item de pedido',
                'db_table': 'order_item',
            },
        ),
    ]
