# Generated by Django 4.1.1 on 2022-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_date_delivered_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(db_column='items', to='sales.orderitem', verbose_name='Item de productos'),
        ),
    ]
