# Generated by Django 3.2.4 on 2022-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('DNI', 'Documento de identidad'), ('RUC', 'Registro Unico de Contribuyente'), ('PAS', 'Pasaporte')], db_column='document_type', max_length=3)),
                ('document_number', models.CharField(db_column='document_number', max_length=15, unique=True)),
                ('name_client', models.CharField(db_column='name_client', max_length=30)),
                ('type_client', models.CharField(db_column='type_client', max_length=30)),
                ('address', models.CharField(db_column='address', max_length=50)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=15)),
            ],
            options={
                'verbose_name': 'Clientes',
                'db_table': 'clients',
            },
        ),
    ]
