# Generated by Django 4.1.1 on 2022-10-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('Restaurantes', 'Restaurantes'), ('Hoteles', 'Hoteles'), ('Tiendas', 'Tiendas'), ('Otro', 'Otro')], db_column='type_client', max_length=30),
        ),
    ]
