# Generated by Django 4.1.1 on 2022-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_type_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(db_column='address', max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(db_column='document_number', max_length=15, unique=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'Documento de identidad'), ('RUC', 'Registro Unico de Contribuyente'), ('PAS', 'Pasaporte')], db_column='document_type', max_length=3, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name_client',
            field=models.CharField(db_column='name_client', max_length=30, verbose_name='Razon social '),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, db_column='phone_number', max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('Restaurantes', 'Restaurantes'), ('Hoteles', 'Hoteles'), ('Tiendas', 'Tiendas'), ('Otro', 'Otro')], db_column='type_client', max_length=30, verbose_name='Tipo de Cliente'),
        ),
    ]
