# Generated by Django 4.1.1 on 2022-10-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='unitmeasure',
            name='unit_measure_category_id',
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='code',
            field=models.CharField(db_column='code', max_length=3, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='name',
            field=models.CharField(db_column='name', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Fecha de Moficación'),
        ),
        migrations.DeleteModel(
            name='UnitMeasureCategory',
        ),
    ]
