# Generated by Django 4.1.1 on 2022-10-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_productcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='Código'),
        ),
    ]
